---
version: '3.7'

services:
  mysql:
    image: ${MYSQL_IMAGE:-percona:ps-5}
    container_name: percona
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=pvats
    volumes:
      - db_mysql:/mysql
  loadbalancer: 
    image: ${NGINX_IMAGE:-nginx:latest}
    volumes:
    - ./lbconfig/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8080:80"
  app1:
    build:
      context: .
      args:
        APPTYPE: 1
    ports:
      - "8081:80"
  app2: 
    build:
      context: .
      args:
        APPTYPE: 2
    ports:
      - "8082:80"
volumes:
  db_mysql: